version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo "Spring Boot build done"
      - mkdir -p target/artifact
      - cp target/*.jar target/artifact/app.jar
artifacts:
  files:
    - app.jar
  base-directory: target/artifact
